### PR TITLE
Update changelog since v4.0.0

### PR DESCRIPTION
**Pull request by thomashoneyman**
**Description of the change**

This PR updates the CHANGELOG in preparation for the upcoming release of this library.

Related: purescript/purescript#3985

### CODE REVIEW

**Comment by JordanMartinez** [comment]
I merged #15 so you can update this PR to include it.

**Review by JordanMartinez — APPROVED** [review]
LGTM

**Comment by JordanMartinez** [comment]
Does #15 need to be added to the changelog? Assuming Gary did accidentally commit it, there was never a release that included it.

**Comment by thomashoneyman** [comment]
I don't think it should be added to the changelog because it should have been invisible to users.

**Pull request merged**
